name: Bazza CI

env:
  VERSION: 1.1.0.${{ github.run_number }}

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/bazza:latest -t ${{ secrets.DOCKER_HUB_USERNAME }}/bazza:${{ env.VERSION }} --file ./Dockerfile --build-arg VERSION=${{ env.VERSION }} .
          
      - name: Push Docker Image
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG   
