name: Bazza CI

env:
  VERSION: 1.1.0.${{ GITHUB_RUN_NUMBER }}

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bazza:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/bazza:${{ VERSION }} 

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
